2019/09/06 19:53:34 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://92.242.140.6:9000", host: "cemigapi.test"
2019/09/06 19:54:01 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://92.242.140.6:9000", host: "cemigapi.test"
2019/09/06 19:55:32 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://92.242.140.6:9000", host: "cemigapi.test"
2019/09/06 20:22:16 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:22:18 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:22:18 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:22:21 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:22:52 [error] 6#6: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:22:53 [error] 6#6: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:22:53 [error] 6#6: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:22:54 [error] 6#6: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:22:54 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:22:54 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:23:13 [error] 6#6: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:23:13 [error] 6#6: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "cemigapi.test"
2019/09/06 20:25:02 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.30.0.4:9000", host: "cemigapi.test"
2019/09/06 20:25:02 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.30.0.4:9000", host: "cemigapi.test"
2019/09/06 20:25:03 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.30.0.4:9000", host: "cemigapi.test"
2019/09/06 20:25:03 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.30.0.4:9000", host: "cemigapi.test"
2019/09/06 20:25:03 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.30.0.4:9000", host: "cemigapi.test"
2019/09/06 20:25:03 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.30.0.4:9000", host: "cemigapi.test"
2019/09/06 20:25:04 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.30.0.4:9000", host: "cemigapi.test"
2019/09/06 20:25:06 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://172.30.0.4:9000", host: "cemigapi.test"
2019/09/06 20:25:35 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:34 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:35 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:35 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:36 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:36 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:36 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:36 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:37 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:37 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:37 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:39 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:39 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:39 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:39 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:39 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:40 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:40 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:40 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:40 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:42 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:42 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:42 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:42 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:27:42 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.4:9000", host: "cemigapi.test"
2019/09/06 20:30:52 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:30:52 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:30:53 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:30:53 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:30:53 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:30:54 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:30:54 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:30:54 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:30:55 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:31:01 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.4:9000", host: "cemigapi.test"
2019/09/06 20:36:15 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:16 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:16 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:16 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:16 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:55 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:55 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:55 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:56 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:56 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:56 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:56 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:56 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:58 [error] 7#7: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:58 [error] 7#7: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:59 [error] 7#7: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:59 [error] 7#7: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:59 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:36:59 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:37:00 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.4:9000", host: "cemigapi.test"
2019/09/06 20:38:35 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:36 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:36 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:37 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:37 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:37 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:37 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:38 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:38 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:38 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:39 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:39 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:39 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:39 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:39 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:39 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:40 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:40 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:40 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:40 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:40 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:40 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:46 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:46 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:46 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:38:46 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "cemigapi.test"
2019/09/06 20:44:57 [error] 6#6: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.48.1, server: cemigapi.test, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.48.4:9000", host: "cemigapi.test"
2019/09/09 12:04:40 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:04:42 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:04:42 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:04:42 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:04:43 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:04:43 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:04:43 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:04:44 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:08:08 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:08:08 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:08:09 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:08:09 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:08:12 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:08:12 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:08:12 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:08:13 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:08:13 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:11:14 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:11:15 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:11:15 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:11:15 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:11:16 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:11:17 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:11:17 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:11:18 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/dashboard HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test"
2019/09/09 12:21:04 [error] 7#7: *159 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/api/stats HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test", referrer: "http://cemigapi.test/horizon/dashboard"
2019/09/09 12:21:04 [error] 6#6: *157 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/api/masters HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test", referrer: "http://cemigapi.test/horizon/dashboard"
2019/09/09 12:21:04 [error] 6#6: *158 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.160.1, server: cemigapi.test, request: "GET /horizon/api/workload HTTP/1.1", upstream: "fastcgi://192.168.160.5:9000", host: "cemigapi.test", referrer: "http://cemigapi.test/horizon/dashboard"
2019/11/05 13:19:10 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:10 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test", referrer: "http://arquivei.test/"
2019/11/05 13:19:11 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:11 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:12 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:12 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:18 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:21 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:31 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:32 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:32 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:32 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:33 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:48 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:19:48 [error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
2019/11/05 13:42:06 [error] 6#6: *22 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: arquivei.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "arquivei.test"
